name: checkov-app
on:
  #push:
  #  paths:
  #    - 'app/**'
  pull_request:
    types: [opened]
    paths: 
      - 'app/**'
    
env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@master
      - uses:  'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: app/
          quiet: true # optional: display only failed checks
          output_format: github_failed_only
          
      - name: Build Docker Image
       # if: ${{ steps.checkov.outcome == 'success' }}
        run: |
         docker build -t checkov-demo:latest app/.
         gcloud builds submit --tag gcr.io/omni-new/checkov-demo app/DockerFile
         
      - name: Post comment to GitHub PR
        uses: mshick/add-pr-comment@v1
        if: ${{ failure() && steps.checkov.outcome == 'failure' }}
        with:
         repo-token: ${{ secrets.TOKEN }}
         message: |
            ${{ env.CHECKOV_RESULTS }}
    
